networks:
  backend:
    name: backend
    external: true

services:
  bff_api:
    container_name: bff_api
    image: bff_api
    build:
      context: .
      dockerfile: BFF.Web.API/Development.Dockerfile
    ports:
      - "5030:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - /home/ellison/source/repos/egress-backend/src/egress_app/Egress.API/files:/files
    networks:
      - backend